import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { LayoutGrid, Database, Zap, MessageSquare, Mic } from 'lucide-react';
const AureonDock = ({ activeView, onNavigate, onVoiceClick }) => {
    const items = [
        { id: 'dashboard', icon: _jsx(LayoutGrid, { size: 22 }), label: 'Home' },
        { id: 'agency', icon: _jsx(Database, { size: 22 }), label: 'Datos' },
        { id: 'flow', icon: _jsx(Zap, { size: 22 }), label: 'RAG' },
        { id: 'chat', icon: _jsx(MessageSquare, { size: 22 }), label: 'Chat' },
    ];
    return (_jsx("div", { className: "fixed bottom-6 left-1/2 -translate-x-1/2 z-50 w-[90%] max-w-md md:hidden", children: _jsx("div", { className: "relative flex items-center justify-between px-6 py-4 bg-black/40 backdrop-blur-2xl border border-white/10 rounded-[2.5rem] shadow-[0_20px_50px_rgba(0,0,0,0.5)]", children: _jsxs("div", { className: "flex items-center gap-1 w-full justify-around", children: [items.slice(0, 2).map((item) => (_jsxs("button", { onClick: () => onNavigate(item.id), className: `flex flex-col items-center justify-center gap-1 p-2 rounded-2xl transition-all relative ${activeView === item.id ? 'text-white' : 'text-gray-500 hover:text-gray-300'}`, children: [_jsx("div", { className: activeView === item.id ? 'text-emerald-400 drop-shadow-[0_0_8px_rgba(52,211,153,0.5)]' : '', children: item.icon }), _jsx("span", { className: `text-[10px] font-medium leading-none ${activeView === item.id ? 'text-white' : 'text-gray-500'}`, children: item.label === 'Home' ? 'Inicio' : item.label })] }, item.id))), _jsxs("button", { onClick: onVoiceClick, className: "group flex flex-col items-center justify-center gap-1 p-2 rounded-2xl relative", children: [_jsx("div", { className: "w-[22px] h-[22px]" }), _jsx("div", { className: "absolute -top-10 left-1/2 -translate-x-1/2", children: _jsxs("div", { className: "relative", children: [_jsx("div", { className: "absolute inset-0 bg-emerald-500/20 blur-2xl rounded-full scale-150 animate-pulse" }), _jsx("div", { className: "relative w-14 h-14 bg-gradient-to-tr from-emerald-600 to-teal-400 rounded-full flex items-center justify-center shadow-[0_10px_30px_rgba(16,185,129,0.4)] border-4 border-black group-active:scale-90 transition-transform", children: _jsx(Mic, { size: 24, className: "text-white fill-white/20" }) })] }) }), _jsx("span", { className: "text-[10px] font-bold text-emerald-400 tracking-wide uppercase drop-shadow-md", children: "Savara" })] }), items.slice(2, 4).map((item) => (_jsxs("button", { onClick: () => onNavigate(item.id), className: `flex flex-col items-center justify-center gap-1 p-2 rounded-2xl transition-all relative ${activeView === item.id ? 'text-white' : 'text-gray-500 hover:text-gray-300'}`, children: [_jsx("div", { className: activeView === item.id ? 'text-emerald-400 drop-shadow-[0_0_8px_rgba(52,211,153,0.5)]' : '', children: item.icon }), _jsx("span", { className: `text-[10px] font-medium leading-none ${activeView === item.id ? 'text-white' : 'text-gray-500'}`, children: item.label })] }, item.id)))] }) }) }));
};
export default AureonDock;
