import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Database, Zap, Check, Users, Target, CheckSquare, Calendar, Clock, LayoutGrid, Plus, ArrowUpRight, Mic, Briefcase, Activity, FileText as FileIcon } from 'lucide-react';
import { getCurrentBrand } from '../config/branding';
const brand = getCurrentBrand();
const Dashboard = ({ user, tasks, leads, notionDocs, events, clients, trainingMode, onNavigate, onToggleTask }) => {
    const activeTasks = tasks.filter(t => !t.completed);
    // WIDGET REGISTRY
    const WIDGETS = {
        status: (_jsxs("div", { className: "col-span-full flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white/[0.02] border border-white/5 p-6 rounded-[2.5rem] liquid-glass", children: [_jsx("div", { className: "flex-1 w-full md:w-auto", children: _jsxs("div", { className: "p-3 bg-indigo-500/10 border border-indigo-500/20 rounded-2xl", style: { backgroundColor: `${brand.colors.primary}1a`, borderColor: `${brand.colors.primary}33` }, children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx(Database, { size: 24, style: { color: brand.colors.primary } }), _jsx("h2", { className: "text-sm font-bold text-white", children: "EST. DEL SISTEMA" })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "text-[10px] text-gray-400", children: "STATUS" }), _jsx("div", { className: "w-1.5 h-1.5 rounded-full animate-pulse shadow-[0_0_8px_currentColor]", style: { backgroundColor: brand.colors.primary, color: brand.colors.primary } }), _jsx("span", { className: "text-[10px] font-bold uppercase tracking-widest", style: { color: brand.colors.primary }, children: brand.tagline })] }), _jsx("div", { className: "text-[10px] font-mono text-gray-500", children: new Date().toLocaleTimeString() })] })] }) }), _jsx("div", { className: "flex gap-2", children: _jsxs("div", { className: "px-4 py-2 bg-white/5 border border-white/10 rounded-2xl flex items-center gap-3", children: [_jsx(Activity, { size: 14, className: "text-blue-400" }), _jsx("span", { className: "text-xs font-bold text-gray-300", children: "Health: Quantum Stable" })] }) })] }, "status")),
        hub: (_jsx("div", { className: "col-span-full grid grid-cols-2 md:grid-cols-4 gap-4", children: [
                { label: 'Hub Operativo', icon: _jsx(Target, { size: 18 }), status: 'Online', color: 'text-emerald-400', view: 'agency' },
                { label: 'Clientes 2026', icon: _jsx(Users, { size: 18 }), status: `${clients.length} Activos`, color: 'text-blue-400', view: 'agency' },
                { label: 'Tareas Ops', icon: _jsx(CheckSquare, { size: 18 }), status: `${activeTasks.length} Pendientes`, color: 'text-amber-400', view: 'board' },
                { label: 'Aureon Brain', icon: _jsx(Zap, { size: 18 }), status: 'Syncing', color: 'text-purple-400', view: 'flow' }
            ].map((item, i) => (_jsxs("button", { onClick: () => onNavigate(item.view), className: "bg-[#0a0a0c] border border-white/5 rounded-3xl p-5 hover:bg-white/[0.04] hover:border-white/10 hover:shadow-2xl transition-all cursor-pointer group liquid-glass text-left w-full active:scale-95", children: [_jsx("div", { className: `mb-4 transition-colors ${item.color}`, children: item.icon }), _jsxs("div", { className: "space-y-1", children: [_jsx("div", { className: "text-xs font-bold text-gray-300 tracking-tight group-hover:text-white transition-colors", children: item.label }), _jsx("div", { className: "text-[10px] text-gray-600 uppercase tracking-widest", children: item.status })] })] }, i))) }, "hub")),
        tasks: (_jsxs("section", { className: "lg:col-span-8 bg-[#0a0a0c] border border-white/5 rounded-[2.5rem] p-8 space-y-6 liquid-glass", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsxs("h3", { className: "text-lg font-bold text-white tracking-tight flex items-center gap-2", children: [_jsx(CheckSquare, { size: 18, className: "text-amber-400" }), "Foco Vital"] }), _jsx("button", { onClick: () => onNavigate('board'), className: "text-[10px] font-black uppercase tracking-widest text-gray-500 hover:text-white transition-colors", children: "Ver Kanban" })] }), _jsx("div", { className: "space-y-3", children: activeTasks.length === 0 ? (_jsx("div", { className: "text-center py-10 text-gray-600 text-sm italic", children: "Sin tareas pendientes para hoy." })) : (activeTasks.slice(0, 4).map(task => (_jsxs("div", { className: "group bg-white/[0.02] border border-white/5 p-4 rounded-2xl flex items-center justify-between hover:bg-white/[0.04] hover:border-white/10 transition-all", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: `w-1.5 h-1.5 rounded-full ${task.priority === 'high' ? 'bg-red-500 shadow-[0_0_10px_#ef4444]' : 'bg-gray-600'}` }), _jsxs("div", { children: [_jsx("div", { className: "text-sm font-medium text-gray-200 group-hover:text-white transition-colors", children: task.title }), _jsxs("div", { className: "flex gap-2 mt-1", children: [task.priority === 'high' && _jsx("span", { className: "text-[9px] font-black text-red-500/70 uppercase tracking-widest", children: "Alta Prioridad" }), task.organizationId && _jsx("span", { className: "text-[9px] font-black text-blue-500/60 uppercase tracking-widest", children: task.organizationId })] })] })] }), _jsx("button", { onClick: () => onToggleTask?.(task.id), className: "w-8 h-8 rounded-full border border-white/10 hover:border-emerald-500/50 hover:bg-emerald-500/10 transition-all flex items-center justify-center group/check active:scale-90", children: _jsx(Check, { size: 14, className: "text-emerald-500 opacity-0 group-hover/check:opacity-100 transition-opacity" }) })] }, task.id)))) })] }, "tasks")),
        portfolio: (_jsxs("section", { className: "lg:col-span-4 bg-[#0a0a0c] border border-white/5 rounded-[2.5rem] p-6 liquid-glass", children: [_jsx("div", { className: "flex justify-between items-center mb-6 px-2", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Briefcase, { size: 18, className: "text-blue-500" }), _jsx("h3", { className: "text-lg font-bold text-white tracking-tight", children: "Cartera 2026" })] }) }), _jsx("div", { className: "space-y-3", children: clients.slice(0, 4).map((client) => (_jsxs("button", { onClick: () => onNavigate('agency'), className: "w-full text-left group bg-white/[0.02] border border-white/5 rounded-2xl p-4 hover:bg-white/[0.05] hover:border-white/10 transition-all cursor-pointer flex justify-between items-center relative overflow-hidden active:scale-[0.98]", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 bg-gradient-to-tr from-white/5 to-white/10 border border-white/10 rounded-xl flex items-center justify-center text-gray-500 group-hover:text-blue-400 transition-colors", children: client.logo || _jsx(LayoutGrid, { size: 18 }) }), _jsxs("div", { children: [_jsx("div", { className: "text-sm font-bold text-gray-300 group-hover:text-white transition-colors", children: client.name }), _jsx("div", { className: "text-[10px] text-gray-600 uppercase tracking-widest", children: client.type })] })] }), _jsx(ArrowUpRight, { size: 14, className: "text-gray-700 group-hover:text-white transition-colors" })] }, client.id))) }), _jsxs("button", { className: "w-full mt-6 py-3 bg-blue-600 hover:bg-blue-500 border border-blue-400/30 rounded-2xl text-white text-[10px] font-black uppercase tracking-[0.2em] shadow-[0_4px_20px_rgba(37,99,235,0.4)] transition-all flex items-center justify-center gap-2", children: [_jsx(Plus, { size: 14 }), " Nuevo Cliente"] })] }, "portfolio")),
        links: (_jsxs("section", { className: "lg:col-span-8 bg-[#0a0a0c] border border-white/5 rounded-[2.5rem] p-8 liquid-glass", children: [_jsxs("div", { className: "flex justify-between items-center mb-6", children: [_jsx("h3", { className: "text-lg font-bold text-white tracking-tight", children: "Neural Links" }), _jsx("span", { className: "text-[10px] font-black text-emerald-500 bg-emerald-500/10 px-3 py-1 rounded-full border border-emerald-500/20 uppercase tracking-widest", children: "Active Hub" })] }), _jsx("div", { className: "grid grid-cols-2 md:grid-cols-5 gap-4", children: [
                        { name: 'Supabase', icon: _jsx(Database, { size: 16 }), color: 'text-emerald-500' },
                        { name: 'Notion', icon: _jsx(FileIcon, { size: 16 }), color: 'text-white' },
                        { name: 'Google', icon: _jsx(Zap, { size: 16 }), color: 'text-blue-500' },
                        { name: 'n8n', icon: _jsx(Activity, { size: 16 }), color: 'text-orange-500' },
                        { name: 'Flowise', icon: _jsx(Mic, { size: 16 }), color: 'text-purple-500' }
                    ].map((app, i) => (_jsxs("div", { className: "flex flex-col items-center gap-2 p-4 bg-white/5 rounded-3xl border border-white/5 group hover:bg-white/10 transition-all cursor-pointer", children: [_jsx("div", { className: `p-3 rounded-2xl bg-black/40 ${app.color}`, children: app.icon }), _jsx("span", { className: "text-[10px] font-bold text-gray-500 group-hover:text-gray-300 transition-colors", children: app.name })] }, i))) })] }, "links")),
        chronos: (_jsxs("section", { className: "lg:col-span-4 bg-[#0a0a0c] border border-white/5 rounded-[2.5rem] p-6 liquid-glass flex flex-col", children: [_jsx("div", { className: "flex justify-between items-center mb-6 px-2", children: _jsxs("div", { className: "flex items-center gap-2 text-gray-400", children: [_jsx(Calendar, { size: 18 }), _jsx("h3", { className: "text-lg font-bold tracking-tight text-white", children: "Chronos" })] }) }), _jsx("div", { className: "flex-1 space-y-4", children: events.length === 0 ? (_jsxs("div", { className: "flex flex-col items-center justify-center h-full text-center space-y-3 opacity-40 py-10", children: [_jsx(Clock, { size: 32 }), _jsx("div", { className: "text-[10px] font-black uppercase tracking-widest", children: "Sin eventos pr\u00F3ximos" })] })) : (events.map(event => (_jsxs("div", { className: "bg-white/5 p-4 rounded-2xl border border-white/5 space-y-1", children: [_jsx("div", { className: "text-xs font-bold text-white", children: event.title }), _jsxs("div", { className: "text-[10px] text-gray-500 flex justify-between items-center", children: [_jsx("span", { children: event.startTime.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }), event.link && _jsx(ArrowUpRight, { size: 10, className: "text-blue-400" })] })] }, event.id)))) })] }, "chronos")),
        voice: (_jsxs("section", { className: "lg:col-span-8 relative overflow-hidden bg-[#0a0a0c] border border-white/5 rounded-[2.5rem] p-8 group liquid-glass", children: [_jsx("div", { className: "absolute -right-20 -top-20 w-64 h-64 bg-emerald-500/10 blur-[100px] rounded-full group-hover:bg-emerald-500/20 transition-all duration-1000" }), _jsxs("div", { className: "relative z-10 space-y-6", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-2xl text-emerald-500", children: _jsx(Zap, { size: 24 }) }), _jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold text-white tracking-tight", children: "Aureon Brain" }), _jsx("p", { className: "text-sm text-gray-500", children: "Inteligencia Generativa Activa" })] })] }), _jsx("div", { className: "px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 rounded-full text-[10px] font-black uppercase tracking-widest text-emerald-500 animate-pulse", children: "Live" })] }), _jsx("div", { className: "bg-black/40 border border-white/5 rounded-2xl p-6", children: _jsx("p", { className: "text-sm text-gray-400 leading-relaxed italic", children: "\"Analizando tendencias de la Cartera 2026. Sugiero priorizar el onboarding de Cl\u00EDnica Pro Salud para optimizar el flujo de caja del Q1.\"" }) }), _jsx("div", { className: "flex flex-wrap gap-2", children: ['Planear Día', 'Resumen Clientes', 'Nueva Tarea'].map(cmd => (_jsx("button", { onClick: (e) => {
                                    e.stopPropagation();
                                    alert(`Aureon Voice Command: "${cmd}" inicializado.`);
                                }, className: "px-4 py-2 bg-emerald-500/10 border border-emerald-500/20 text-emerald-500 text-[9px] font-black uppercase tracking-widest rounded-xl hover:bg-emerald-500/20 transition-all active:scale-95", children: cmd }, cmd))) })] })] }, "voice")),
        training: trainingMode?.active ? (_jsxs("section", { className: "lg:col-span-4 bg-amber-500/10 border border-amber-500/20 rounded-[2.5rem] p-8 flex flex-col items-center justify-center text-center space-y-4 liquid-glass", children: [_jsx("div", { className: "w-12 h-12 bg-amber-500/20 rounded-2xl flex items-center justify-center text-amber-500 animate-bounce", children: _jsx(Activity, { size: 24 }) }), _jsxs("div", { className: "space-y-1", children: [_jsx("h4", { className: "text-lg font-bold text-amber-500 tracking-tight", children: "Modo Entrenamiento" }), _jsx("p", { className: "text-xs text-amber-500/60 uppercase tracking-widest font-black leading-tight", children: trainingMode.reason })] }), _jsx("button", { className: "px-6 py-2 bg-amber-500 text-black text-[10px] font-black uppercase tracking-widest rounded-full hover:bg-amber-400 transition-all", children: "Finalizar Sesi\u00F3n" })] }, "training")) : null
    };
    const layout = user.layoutConfig || ['status', 'hub', 'tasks', 'portfolio', 'links', 'chronos'];
    return (_jsxs("main", { className: "px-4 sm:px-6 lg:px-8 pb-32 max-w-7xl mx-auto space-y-6 animate-in fade-in duration-1000", children: [_jsx("div", { className: "grid grid-cols-1 lg:grid-cols-12 gap-6", children: layout.map(widgetId => WIDGETS[widgetId] || null) }), _jsxs("div", { className: "flex flex-col items-center justify-center pt-10 pb-6 space-y-4 opacity-30 mt-12", children: [_jsx("div", { className: "text-[10px] font-black text-gray-500 uppercase tracking-[0.5em]", children: brand.name }), _jsxs("div", { className: "flex gap-4", children: [_jsx("div", { className: "w-1 h-1 bg-emerald-500 rounded-full animate-pulse" }), _jsx("div", { className: "w-1 h-1 bg-blue-500 rounded-full animate-pulse delay-700" }), _jsx("div", { className: "w-1 h-1 bg-purple-500 rounded-full animate-pulse delay-1000" })] })] })] }));
};
export default Dashboard;
