import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Users, Briefcase, CheckSquare, Search, Plus, ExternalLink, ChevronRight, Building } from 'lucide-react';
import { getCurrentBrand } from '../config/branding';
const NotionView = ({ clients, services, tasks, onToggleTask }) => {
    const brand = getCurrentBrand();
    const [activeTab, setActiveTab] = useState('clientes');
    const [searchQuery, setSearchQuery] = useState('');
    const tabs = [
        { id: 'clientes', label: 'Clientes', icon: _jsx(Users, { size: 16 }), count: clients.length },
        { id: 'servicios', label: 'Servicios', icon: _jsx(Briefcase, { size: 16 }), count: services.length },
        { id: 'tareas', label: 'Tareas', icon: _jsx(CheckSquare, { size: 16 }), count: tasks.length },
    ];
    const filteredClients = clients.filter(c => c.name.toLowerCase().includes(searchQuery.toLowerCase()));
    const filteredTasks = tasks.filter(t => t.title.toLowerCase().includes(searchQuery.toLowerCase()));
    // Filter tasks by current user for the 'Tareas' tab focus
    const myTasks = tasks.filter(t => (t.assignedTo === searchQuery) || // Allows searching for others
        (t.assignedTo && (t.assignedTo.includes('Christian') || t.assignedTo.includes('Andrea'))) // Placeholder for session filter in this view if needed
    );
    return (_jsxs("div", { className: "p-6 md:p-8 max-w-6xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-500", children: [_jsxs("div", { className: "flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-white tracking-tight", children: "Datos" }), _jsx("p", { className: "text-sm text-gray-500", children: "Informaci\u00F3n sincronizada desde Notion" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("div", { className: "relative", children: [_jsx(Search, { size: 16, className: "absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" }), _jsx("input", { type: "text", value: searchQuery, onChange: (e) => setSearchQuery(e.target.value), placeholder: "Buscar...", className: "pl-9 pr-4 py-2 bg-white/5 border border-white/10 rounded-xl text-sm focus:outline-none focus:ring-1 focus:ring-white/20 w-48" })] }), _jsx("button", { className: "p-2 rounded-xl text-white flex items-center gap-2", style: { backgroundColor: brand.colors.primary }, children: _jsx(Plus, { size: 16 }) })] })] }), _jsx("div", { className: "flex gap-1 p-1 bg-white/[0.02] border border-white/5 rounded-xl mb-6", children: tabs.map((tab) => (_jsxs("button", { onClick: () => setActiveTab(tab.id), className: `flex-1 flex items-center justify-center gap-2 py-2.5 px-4 rounded-lg transition-all text-sm font-medium ${activeTab === tab.id
                        ? 'bg-white/10 text-white'
                        : 'text-gray-500 hover:text-white hover:bg-white/5'}`, children: [tab.icon, _jsx("span", { children: tab.label }), _jsx("span", { className: "text-[10px] font-bold px-1.5 py-0.5 rounded bg-white/10", children: tab.count })] }, tab.id))) }), _jsxs("div", { className: "bg-white/[0.01] border border-white/5 rounded-2xl overflow-hidden", children: [activeTab === 'clientes' && (_jsx("div", { className: "divide-y divide-white/5", children: filteredClients.length > 0 ? filteredClients.map((client) => (_jsxs("div", { className: "flex items-center gap-4 p-4 hover:bg-white/[0.02] transition-all", children: [_jsx("div", { className: "w-10 h-10 rounded-xl flex items-center justify-center text-white font-bold text-sm shrink-0", style: { backgroundColor: `${brand.colors.accent}30` }, children: client.name.slice(0, 2).toUpperCase() }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "text-sm font-medium text-white truncate", children: client.name }), _jsx("p", { className: "text-xs text-gray-500 truncate", children: client.email || 'Sin email' })] }), _jsx("div", { className: "hidden md:flex items-center gap-4 text-xs text-gray-500", children: _jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Building, { size: 12 }), client.company || 'Empresa'] }) }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-[9px] font-bold uppercase px-2 py-1 rounded-full", style: {
                                                backgroundColor: client.status === 'active' ? `${brand.colors.success}15` : `${brand.colors.warning}15`,
                                                color: client.status === 'active' ? brand.colors.success : brand.colors.warning
                                            }, children: client.status === 'active' ? 'Activo' : 'Pendiente' }), _jsx(ChevronRight, { size: 16, className: "text-gray-600" })] })] }, client.id))) : (_jsxs("div", { className: "p-8 text-center text-gray-600", children: [_jsx(Users, { size: 32, className: "mx-auto mb-3 opacity-50" }), _jsx("p", { className: "text-sm", children: "No hay clientes que mostrar" })] })) })), activeTab === 'servicios' && (_jsx("div", { className: "divide-y divide-white/5", children: services.length > 0 ? services.map((service) => (_jsxs("div", { className: "flex items-center gap-4 p-4 hover:bg-white/[0.02] transition-all", children: [_jsx("div", { className: "w-10 h-10 rounded-xl flex items-center justify-center shrink-0", style: { backgroundColor: `${brand.colors.primary}20`, color: brand.colors.primary }, children: _jsx(Briefcase, { size: 18 }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: "text-sm font-medium text-white truncate", children: service.name }), _jsx("p", { className: "text-xs text-gray-500", children: service.frequency === 'monthly' ? 'Mensual' : 'Pago Único' })] }), _jsx("span", { className: "text-[9px] font-bold uppercase px-2 py-1 rounded-full", style: {
                                        backgroundColor: `${brand.colors.success}15`,
                                        color: brand.colors.success
                                    }, children: "Activo" })] }, service.id))) : (_jsxs("div", { className: "p-8 text-center text-gray-600", children: [_jsx(Briefcase, { size: 32, className: "mx-auto mb-3 opacity-50" }), _jsx("p", { className: "text-sm", children: "No hay servicios que mostrar" })] })) })), activeTab === 'tareas' && (_jsx("div", { className: "divide-y divide-white/5", children: filteredTasks.length > 0 ? filteredTasks.map((task) => (_jsxs("div", { className: "flex items-center gap-4 p-4 hover:bg-white/[0.02] transition-all", children: [_jsx("button", { onClick: () => onToggleTask?.(task.id), className: "shrink-0 transition-transform active:scale-90", children: task.completed ? (_jsx("div", { className: "w-5 h-5 rounded-full flex items-center justify-center", style: { backgroundColor: brand.colors.success }, children: _jsx(CheckSquare, { size: 12, className: "text-white" }) })) : (_jsx("div", { className: "w-5 h-5 rounded-full border-2 border-gray-600 hover:border-white/50 transition-colors" })) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("p", { className: `text-sm font-medium truncate ${task.completed ? 'text-gray-500 line-through' : 'text-white'}`, children: task.title }), _jsxs("div", { className: "flex items-center gap-2 mt-0.5", children: [task.assignedTo && (_jsx("span", { className: "text-[9px] font-bold text-gray-500", children: task.assignedTo })), task.tags?.[0] && (_jsxs("span", { className: "text-[9px] text-gray-600", children: ["\u2022 ", task.tags[0]] }))] })] }), _jsx("span", { className: "text-[9px] font-bold uppercase px-2 py-1 rounded-full", style: {
                                        backgroundColor: task.priority === 'high' ? `${brand.colors.danger}15` :
                                            task.priority === 'medium' ? `${brand.colors.warning}15` : `${brand.colors.muted}15`,
                                        color: task.priority === 'high' ? brand.colors.danger :
                                            task.priority === 'medium' ? brand.colors.warning : brand.colors.muted
                                    }, children: task.priority === 'high' ? 'Alta' : task.priority === 'medium' ? 'Media' : 'Baja' })] }, task.id))) : (_jsxs("div", { className: "p-8 text-center text-gray-600", children: [_jsx(CheckSquare, { size: 32, className: "mx-auto mb-3 opacity-50" }), _jsx("p", { className: "text-sm", children: "No hay tareas que mostrar" })] })) }))] }), _jsx("div", { className: "mt-4 flex justify-end", children: _jsxs("a", { href: "https://notion.so", target: "_blank", className: "flex items-center gap-2 text-xs text-gray-600 hover:text-white transition-colors", children: [_jsx(ExternalLink, { size: 12 }), "Abrir en Notion"] }) })] }));
};
export default NotionView;
