import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Zap, Settings, LogOut, ChevronLeft, ChevronRight, Home, Folder, BookOpen, User, ChevronsUpDown, Check } from 'lucide-react';
import { getCurrentBrand } from '../config/branding';
const Sidebar = ({ activeView, onNavigate, user, onLogout, onOpenSettings, organizations, currentOrgId, onSwitchOrg, mobileOpen, onMobileClose }) => {
    // Get brand based on current Org
    const brand = getCurrentBrand(currentOrgId);
    const [isCollapsed, setIsCollapsed] = useState(true);
    const [isOrgMenuOpen, setIsOrgMenuOpen] = useState(false);
    const menuItems = [
        { id: 'home', label: 'Inicio', icon: _jsx(Home, { size: 20 }) },
        { id: 'agency', label: 'Datos', icon: _jsx(Folder, { size: 20 }) },
        { id: 'flow', label: 'RAG', icon: _jsx(BookOpen, { size: 20 }) },
        { id: 'connections', label: 'Conexiones', icon: _jsx(Zap, { size: 20 }) },
        { id: 'team', label: 'Equipo', icon: _jsx(User, { size: 20 }) },
    ];
    return (_jsxs("aside", { className: `fixed left-0 top-0 bottom-0 ${mobileOpen ? 'flex w-64' : 'hidden md:flex'} flex-col z-50 transition-all duration-300 ease-out bg-[#020203]/90 backdrop-blur-2xl border-r border-white/5 ${isCollapsed && !mobileOpen ? 'w-[72px]' : 'w-60' // Force expand on mobile
        }`, children: [_jsxs("div", { className: "relative", children: [_jsxs("button", { onClick: () => !isCollapsed && setIsOrgMenuOpen(!isOrgMenuOpen), className: `w-full p-4 flex items-center gap-3 border-b border-white/5 hover:bg-white/5 transition-colors ${isCollapsed ? 'justify-center cursor-default' : 'cursor-pointer'}`, children: [_jsx("div", { className: "w-10 h-10 rounded-xl flex items-center justify-center text-white font-black text-sm shrink-0 shadow-lg shadow-purple-500/10", style: { background: `linear-gradient(135deg, ${brand.colors.primary}, ${brand.colors.accent})` }, children: brand.name.charAt(0) }), !isCollapsed && (_jsxs("div", { className: "flex-1 overflow-hidden text-left", children: [_jsx("h2", { className: "text-sm font-black tracking-tight text-white truncate", children: brand.name }), _jsx("p", { className: "text-[9px] font-bold text-gray-500 uppercase tracking-wider truncate", children: brand.tagline })] })), !isCollapsed && (_jsx(ChevronsUpDown, { size: 14, className: "text-gray-500" }))] }), isOrgMenuOpen && !isCollapsed && (_jsxs("div", { className: "absolute top-full left-2 right-2 mt-1 py-1 rounded-xl bg-[#0A0A0A] border border-white/10 shadow-2xl z-50 animate-in fade-in slide-in-from-top-2 duration-200", children: [_jsx("div", { className: "px-3 py-2 text-[10px] font-bold text-gray-500 uppercase", children: "Organizaciones" }), organizations.map(org => (_jsxs("button", { onClick: () => {
                                    onSwitchOrg(org.id);
                                    setIsOrgMenuOpen(false);
                                }, className: "w-full flex items-center gap-2 px-3 py-2 text-sm text-left hover:bg-white/5 transition-colors", children: [_jsx("div", { className: `w-4 h-4 rounded-full border border-white/20 flex items-center justify-center ${currentOrgId === org.id ? 'bg-white text-black' : 'text-transparent'}`, children: currentOrgId === org.id && _jsx(Check, { size: 10, strokeWidth: 4 }) }), _jsx("span", { className: currentOrgId === org.id ? 'text-white font-semibold' : 'text-gray-400', children: org.name })] }, org.id)))] }))] }), _jsx("nav", { className: "flex-1 py-4 px-2 space-y-1", children: menuItems.map((item) => (_jsxs("button", { onClick: () => onNavigate(item.id), title: isCollapsed ? item.label : undefined, className: `w-full flex items-center gap-3 px-3 py-3 rounded-xl transition-all duration-200 group ${activeView === item.id
                        ? 'bg-white/10 text-white'
                        : 'text-gray-500 hover:text-white hover:bg-white/5'} ${isCollapsed ? 'justify-center' : ''}`, children: [_jsx("div", { className: `shrink-0 transition-transform duration-200 ${activeView === item.id ? 'scale-110' : 'group-hover:scale-110'}`, children: item.icon }), !isCollapsed && (_jsx("span", { className: "text-sm font-semibold tracking-tight truncate", children: item.label })), !isCollapsed && activeView === item.id && (_jsx("div", { className: "ml-auto w-1.5 h-1.5 rounded-full", style: { backgroundColor: brand.colors.primary, boxShadow: `0 0 8px ${brand.colors.primary}` } }))] }, item.id))) }), _jsxs("div", { className: "p-3 border-t border-white/5 space-y-2", children: [_jsxs("button", { onClick: onOpenSettings, className: `w-full p-2 rounded-xl bg-white/[0.03] border border-white/5 flex items-center gap-2 hover:bg-white/[0.06] transition-all ${isCollapsed ? 'justify-center' : ''}`, children: [_jsx("div", { className: "w-8 h-8 rounded-lg bg-gray-800 border border-white/10 flex items-center justify-center overflow-hidden shrink-0", children: _jsx("img", { src: `https://ui-avatars.com/api/?name=${encodeURIComponent(user.name)}&background=${brand.colors.primary.slice(1)}&color=fff&size=64`, alt: user.name, className: "w-full h-full object-cover" }) }), !isCollapsed && (_jsxs("div", { className: "flex flex-col overflow-hidden text-left", children: [_jsx("span", { className: "text-xs font-bold text-white truncate", children: user.name }), _jsx("span", { className: "text-[9px] text-gray-500 truncate", children: user.role })] }))] }), _jsxs("div", { className: `flex ${isCollapsed ? 'flex-col' : ''} gap-1`, children: [_jsx("button", { onClick: onOpenSettings, title: "Configuraci\u00F3n", className: `flex items-center justify-center p-2.5 rounded-xl bg-white/5 border border-white/5 text-gray-500 hover:text-white hover:bg-white/10 transition-all ${isCollapsed ? 'w-full' : 'flex-1'}`, children: _jsx(Settings, { size: 16 }) }), _jsx("button", { onClick: onLogout, title: "Cerrar sesi\u00F3n", className: `flex items-center justify-center p-2.5 rounded-xl bg-red-500/5 border border-red-500/10 text-red-500/50 hover:text-red-500 hover:bg-red-500/10 transition-all ${isCollapsed ? 'w-full' : 'flex-1'}`, children: _jsx(LogOut, { size: 16 }) })] }), _jsxs("button", { onClick: () => setIsCollapsed(!isCollapsed), className: "w-full flex items-center justify-center p-2 rounded-xl text-gray-600 hover:text-white hover:bg-white/5 transition-all", children: [isCollapsed ? _jsx(ChevronRight, { size: 16 }) : _jsx(ChevronLeft, { size: 16 }), !isCollapsed && _jsx("span", { className: "ml-2 text-[10px] font-bold uppercase tracking-wider", children: "Colapsar" })] })] })] }));
};
export default Sidebar;
